'use client';

import PageLayout from '@/components/layout/page-layout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useToast } from '@/components/ui/toast';
import { TokenManager } from '@/lib/token-manager';
import { Radar } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';

interface TradeSignal {
  id: number;
  symbol: string;
  action: string;
  recommendation: string;
  confidence: number;
  summary: string;
  entryPrice: number | null;
  stopLoss: number | null;
  takeProfit: number | null;
  positionSize: number | null;
  status: string;
  provider: string | null;
  generatedAt: string;
}

const ACTION_STYLES: Record<string, string> = {
  BUY: 'bg-green-500/10 text-green-600',
  ADD: 'bg-green-500/10 text-green-600',
  SELL: 'bg-red-500/10 text-red-600',
  TRIM: 'bg-amber-500/10 text-amber-600',
  HOLD: 'bg-muted text-muted-foreground'
};

const FILTERS = [
  { value: '', label: 'All' },
  { value: 'pending_approval', label: 'Approval' },
  { value: 'open', label: 'Open' },
  { value: 'acted', label: 'Acted' },
  { value: 'ignored', label: 'Ignored' }
];

export default function SignalsPage() {
  const { toast } = useToast();
  const router = useRouter();
  const [signals, setSignals] = useState<TradeSignal[]>([]);
  const [filter, setFilter] = useState('');
  const [loading, setLoading] = useState(true);

  const fetchSignals = useCallback(
    async (status: string) => {
      setLoading(true);
      try {
        const url = status ? `/api/user/signals?status=${status}` : '/api/user/signals';
        const response = await TokenManager.makeAuthenticatedRequest(url);
        if (!response.ok) throw new Error('Failed to load signals');
        const data = await response.json();
        setSignals(data.signals ?? []);
      } catch {
        toast('Failed to load signals', 'error');
      } finally {
        setLoading(false);
      }
    },
    [toast]
  );

  useEffect(() => {
    fetchSignals(filter);
  }, [filter, fetchSignals]);

  const markIgnored = async (id: number) => {
    const response = await TokenManager.makeAuthenticatedRequest(`/api/user/signals/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: 'ignored' })
    });
    if (response.ok) {
      toast('Signal ignored', 'success');
      fetchSignals(filter);
    }
  };

  const approve = async (signal: TradeSignal) => {
    try {
      const response = await TokenManager.makeAuthenticatedRequest(
        `/api/user/signals/${signal.id}/approve`,
        { method: 'POST' }
      );
      if (!response.ok) {
        const body = await response.json().catch(() => null);
        throw new Error(body?.error || body?.message || 'Failed to approve signal');
      }
      toast(`Order placed for ${signal.symbol}`, 'success');
      fetchSignals(filter);
    } catch (err) {
      toast(err instanceof Error ? err.message : 'Failed to approve signal', 'error');
    }
  };

  const showOnGraph = (signal: TradeSignal) => {
    const params = new URLSearchParams();
    params.set('symbol', signal.symbol);
    if (signal.entryPrice != null) params.set('entry', String(signal.entryPrice));
    if (signal.stopLoss != null) params.set('sl', String(signal.stopLoss));
    if (signal.takeProfit != null) params.set('tp', String(signal.takeProfit));
    router.push(`/dashboard?${params.toString()}`);
  };

  return (
    <PageLayout>
      <div className="mx-auto max-w-5xl space-y-4 px-4 py-6 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
              <Radar className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">AI Signals</h1>
              <p className="text-sm text-muted-foreground">
                Trade plans generated by the advisor (manual or autonomous).
              </p>
            </div>
          </div>
          <div className="flex gap-1">
            {FILTERS.map(f => (
              <Button
                key={f.value}
                size="sm"
                variant={filter === f.value ? 'default' : 'ghost'}
                onClick={() => setFilter(f.value)}
              >
                {f.label}
              </Button>
            ))}
          </div>
        </div>

        {loading ? (
          <p className="py-16 text-center text-muted-foreground">Loading signals...</p>
        ) : signals.length === 0 ? (
          <div className="rounded-xl border border-dashed py-16 text-center">
            <p className="text-sm text-muted-foreground">No signals yet</p>
          </div>
        ) : (
          <div className="space-y-2">
            {signals.map(signal => (
              <Card key={signal.id}>
                <CardContent className="py-3">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <Badge className={ACTION_STYLES[signal.action] ?? 'bg-muted'}>
                        {signal.action}
                      </Badge>
                      <span className="font-semibold">{signal.symbol}</span>
                      <Badge variant="outline">confidence {signal.confidence}%</Badge>
                      <Badge variant="outline">{signal.status}</Badge>
                      {signal.provider && (
                        <span className="text-xs text-muted-foreground">{signal.provider}</span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <Button size="sm" variant="ghost" onClick={() => showOnGraph(signal)}>
                        Show on graph
                      </Button>
                      <span>{new Date(signal.generatedAt).toLocaleString()}</span>
                      {signal.status === 'pending_approval' && (
                        <>
                          <Button size="sm" variant="default" onClick={() => approve(signal)}>
                            Approve & place
                          </Button>
                          <Button size="sm" variant="ghost" onClick={() => markIgnored(signal.id)}>
                            Reject
                          </Button>
                        </>
                      )}
                      {signal.status === 'open' && (
                        <Button size="sm" variant="ghost" onClick={() => markIgnored(signal.id)}>
                          Ignore
                        </Button>
                      )}
                    </div>
                  </div>
                  <p className="mt-2 text-sm text-muted-foreground">{signal.summary}</p>
                  <div className="mt-2 flex flex-wrap gap-4 text-xs">
                    <span>Entry: {signal.entryPrice ?? '—'}</span>
                    <span>Stop: {signal.stopLoss ?? '—'}</span>
                    <span>Target: {signal.takeProfit ?? '—'}</span>
                    <span>Size: {signal.positionSize ?? '—'}</span>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </PageLayout>
  );
}
