'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { X } from 'lucide-react';

interface AiReportModalProps {
  isVisible: boolean;
  onClose: () => void;
  report: any;
}

export default function AiReportModal({ isVisible, onClose, report }: AiReportModalProps) {
  if (!isVisible || !report) return null;

  const recommendation = report.recommendation ?? 'HOLD';
  const recColor =
    recommendation === 'BUY'
      ? 'text-green-600'
      : recommendation === 'SELL'
        ? 'text-red-600'
        : 'text-yellow-600';

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex justify-between items-center mb-6">
            <div>
              <h2 className="text-2xl font-bold">AI Trading Report</h2>
              <p className="text-gray-600">
                Generated by {report.provider} · {report.generatedAt}
              </p>
            </div>
            <Button onClick={onClose} variant="outline" size="sm">
              <X className="w-4 h-4" />
            </Button>
          </div>

          {/* Summary */}
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Executive Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 mb-4">{report.summary}</p>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="text-center">
                  <div className={`text-2xl font-bold ${recColor}`}>{recommendation}</div>
                  <div className="text-sm text-gray-500">Recommendation</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-gray-800">
                    {report.confidence != null ? `${report.confidence}%` : 'N/A'}
                  </div>
                  <div className="text-sm text-gray-500">Confidence</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-gray-800">
                    {report.priceTargets?.takeProfit ?? 'N/A'}
                  </div>
                  <div className="text-sm text-gray-500">Take Profit</div>
                </div>
                <div className="text-center">
                  <div className="text-2xl font-bold text-gray-800">
                    {report.priceTargets?.stopLoss ?? 'N/A'}
                  </div>
                  <div className="text-sm text-gray-500">Stop Loss</div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Analysis */}
          {report.analysis && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              {report.analysis.technicals && (
                <Card>
                  <CardHeader>
                    <CardTitle>Technical Analysis</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-700 text-sm whitespace-pre-wrap">
                      {report.analysis.technicals}
                    </p>
                  </CardContent>
                </Card>
              )}
              {report.analysis.fundamentals && (
                <Card>
                  <CardHeader>
                    <CardTitle>Fundamentals</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-700 text-sm whitespace-pre-wrap">
                      {report.analysis.fundamentals}
                    </p>
                  </CardContent>
                </Card>
              )}
              {report.analysis.sentiment && (
                <Card>
                  <CardHeader>
                    <CardTitle>Market Sentiment</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-700 text-sm whitespace-pre-wrap">
                      {report.analysis.sentiment}
                    </p>
                  </CardContent>
                </Card>
              )}
              {report.analysis.risks && (
                <Card>
                  <CardHeader>
                    <CardTitle>Risks</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <p className="text-gray-700 text-sm whitespace-pre-wrap">
                      {report.analysis.risks}
                    </p>
                  </CardContent>
                </Card>
              )}
            </div>
          )}

          {/* Trading Plan */}
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Recommended Trading Plan</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-blue-50 p-4 rounded-lg">
                  <div className="font-semibold text-blue-800">Current Price</div>
                  <div className="text-2xl font-bold text-blue-900">
                    {report.priceTargets?.current ?? 'N/A'}
                  </div>
                  <div className="text-sm text-blue-600">Market Entry</div>
                </div>
                <div className="bg-green-50 p-4 rounded-lg">
                  <div className="font-semibold text-green-800">Take Profit</div>
                  <div className="text-2xl font-bold text-green-900">
                    {report.priceTargets?.takeProfit ?? 'N/A'}
                  </div>
                  <div className="text-sm text-green-600">Target Level</div>
                </div>
                <div className="bg-red-50 p-4 rounded-lg">
                  <div className="font-semibold text-red-800">Stop Loss</div>
                  <div className="text-2xl font-bold text-red-900">
                    {report.priceTargets?.stopLoss ?? 'N/A'}
                  </div>
                  <div className="text-sm text-red-600">Risk Management</div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Footer */}
          <div className="text-center text-sm text-gray-500">
            <p>
              Generated on {new Date(report.generatedAt).toLocaleString()} using {report.provider}
            </p>
            <p className="mt-2 font-medium">
              ⚠️ This is AI-generated analysis. Please do your own research before making trading
              decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
