'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AiTradePlan, TradingKey } from '@/types/dashboard';
import { useState } from 'react';
import { X } from 'lucide-react';
import OrderConfirmationDialog from './order-confirmation-dialog';

interface TradePlanModalProps {
  isVisible: boolean;
  plan: AiTradePlan;
  symbol: string;
  companyName?: string;
  tradingKeys: TradingKey[];
  defaultTradingKeyId?: string;
  onClose: () => void;
  onNotification: (n: { message: string; type: 'success' | 'error' | 'info' | 'warning' }) => void;
}

const ACTION_COLORS: Record<string, string> = {
  BUY: 'bg-success text-white',
  ADD: 'bg-success text-white',
  SELL: 'bg-destructive text-white',
  TRIM: 'bg-warning text-white',
  HOLD: 'bg-muted text-muted-foreground'
};

export default function TradePlanModal({
  isVisible,
  plan,
  symbol,
  companyName,
  tradingKeys,
  defaultTradingKeyId,
  onClose,
  onNotification
}: TradePlanModalProps) {
  const [showOrderDialog, setShowOrderDialog] = useState(false);

  if (!isVisible || !plan) return null;

  const action = plan.action ?? 'HOLD';
  const actionColor = ACTION_COLORS[action] ?? ACTION_COLORS.HOLD;

  const copyPlan = () => {
    const lines = [
      `GreedAdvisor AI trade plan — ${symbol}${companyName ? ` (${companyName})` : ''}`,
      `Action: ${action}`,
      `Product: ${plan.productType}`,
      `Confidence: ${plan.confidence}%`,
      `Entry price: ${plan.entryPrice}`,
      plan.stopLoss ? `Stop loss: ${plan.stopLoss}` : '',
      plan.takeProfit ? `Take profit: ${plan.takeProfit}` : '',
      plan.positionSize ? `Suggested size: ${plan.positionSize}` : '',
      plan.riskAmount ? `Suggested risk: ${plan.riskAmount}` : '',
      ``,
      plan.summary
    ].filter(line => line !== '');
    navigator.clipboard?.writeText(lines.join('\n'));
    onNotification({ message: 'Trade plan copied to clipboard', type: 'success' });
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-card rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-4">
            <div>
              <div className="flex items-center gap-3">
                <span className={`px-2 py-1 rounded-md text-xs font-bold ${actionColor}`}>
                  {action}
                </span>
                <h2 className="text-2xl font-bold">{symbol}</h2>
                <span className="px-2 py-1 rounded-md text-xs font-semibold bg-muted text-muted-foreground">
                  {plan.productType}
                </span>
              </div>
              {companyName && <p className="text-muted-foreground mt-1">{companyName}</p>}
              <p className="text-sm text-muted-foreground mt-1">
                Generated by {plan.provider} · {new Date(plan.generatedAt).toLocaleString()}
              </p>
            </div>
            <Button onClick={onClose} variant="outline" size="sm">
              <X className="w-4 h-4" />
            </Button>
          </div>

          {/* Confidence + levels */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
            <div className="bg-muted rounded-lg p-3 text-center">
              <div className="text-2xl font-bold">{plan.confidence}%</div>
              <div className="text-xs text-muted-foreground">Confidence</div>
            </div>
            <div className="bg-primary/10 rounded-lg p-3 text-center">
              <div className="text-xl font-bold text-primary">{plan.entryPrice}</div>
              <div className="text-xs text-primary">Entry</div>
            </div>
            <div className="bg-success/10 rounded-lg p-3 text-center">
              <div className="text-xl font-bold text-success">{plan.takeProfit ?? '—'}</div>
              <div className="text-xs text-success">Take Profit</div>
            </div>
            <div className="bg-destructive/10 rounded-lg p-3 text-center">
              <div className="text-xl font-bold text-destructive">{plan.stopLoss ?? '—'}</div>
              <div className="text-xs text-destructive">Stop Loss</div>
            </div>
          </div>

          {/* Sizing */}
          {(plan.positionSize != null || plan.riskAmount != null) && (
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-4">
              {plan.positionSize != null && (
                <div className="bg-primary/10 rounded-lg p-3 text-center">
                  <div className="text-xl font-bold text-primary">{plan.positionSize}</div>
                  <div className="text-xs text-primary">Suggested size</div>
                </div>
              )}
              {plan.riskAmount != null && (
                <div className="bg-primary/10 rounded-lg p-3 text-center">
                  <div className="text-xl font-bold text-primary">{plan.riskAmount}</div>
                  <div className="text-xs text-primary">Max risk per trade</div>
                </div>
              )}
              {plan.riskPerUnit != null && (
                <div className="bg-primary/10 rounded-lg p-3 text-center">
                  <div className="text-xl font-bold text-primary">{plan.riskPerUnit}</div>
                  <div className="text-xs text-primary">Risk per unit</div>
                </div>
              )}
            </div>
          )}

          <Card className="mb-4">
            <CardHeader>
              <CardTitle>Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground">{plan.summary}</p>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            {plan.analysis.technicals && (
              <Card>
                <CardHeader>
                  <CardTitle>Technicals</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-foreground text-sm whitespace-pre-wrap">
                    {plan.analysis.technicals}
                  </p>
                </CardContent>
              </Card>
            )}
            {plan.analysis.fundamentals && (
              <Card>
                <CardHeader>
                  <CardTitle>Fundamentals</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-foreground text-sm whitespace-pre-wrap">
                    {plan.analysis.fundamentals}
                  </p>
                </CardContent>
              </Card>
            )}
            {plan.analysis.sentiment && (
              <Card>
                <CardHeader>
                  <CardTitle>Sentiment</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-foreground text-sm whitespace-pre-wrap">
                    {plan.analysis.sentiment}
                  </p>
                </CardContent>
              </Card>
            )}
            {plan.analysis.risks && (
              <Card>
                <CardHeader>
                  <CardTitle>Risks</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-foreground text-sm whitespace-pre-wrap">
                    {plan.analysis.risks}
                  </p>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Decision - user always decides */}
          <div className="flex flex-col sm:flex-row gap-2 mt-4">
            <Button onClick={() => setShowOrderDialog(true)} className="flex-1">
              Review Order &amp; Place
            </Button>
            <Button variant="outline" onClick={copyPlan} className="flex-1">
              Copy plan to T212
            </Button>
          </div>
          <p className="text-center text-xs text-muted-foreground mt-3">
            ⚠️ AI-generated analysis only. You decide — do your own research before trading.
          </p>
        </div>
      </div>

      <OrderConfirmationDialog
        isVisible={showOrderDialog}
        plan={plan}
        symbol={symbol}
        companyName={companyName}
        tradingKeys={tradingKeys}
        defaultTradingKeyId={defaultTradingKeyId}
        onClose={() => setShowOrderDialog(false)}
        onNotification={onNotification}
      />
    </div>
  );
}
